# **Deep Residual MLP**

## **1. Import Libraries**

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout, BatchNormalization, Add
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns

## **2. Data Preparation**

In [7]:
import os

def data_preparation(file_path, seed=42):
    df = pd.read_csv(file_path)
    df = df.drop(columns=["CustomerID", "AdvertisingPlatform", "AdvertisingTool"], errors="ignore")

    le = LabelEncoder()
    df["CampaignType"] = le.fit_transform(df["CampaignType"])

    features = [
        "CampaignType", "AdSpend", "ClickThroughRate", "WebsiteVisits", "PagesPerVisit",
        "TimeOnSite", "EmailOpens", "EmailClicks", "PreviousPurchases", "LoyaltyPoints"
    ]
    X = df[features]
    y = df["Conversion"]

    X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2, random_state=seed, stratify=y)
    X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.2, random_state=seed, stratify=y_temp)
    return X_train, X_val, X_test, y_train, y_val, y_test

X_train, X_val, X_test, y_train, y_val, y_test = data_preparation('../dataset/digital_marketing_campaign_dataset.csv')

## **3. Preprocessing**

In [8]:
features = [
    'AdSpend', 'ClickThroughRate', 'WebsiteVisits', 'PagesPerVisit',
    'TimeOnSite', 'EmailOpens', 'EmailClicks', 'PreviousPurchases', 'LoyaltyPoints', 'CampaignType'
]

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train[features])
X_val   = scaler.transform(X_val[features])
X_test  = scaler.transform(X_test[features])

## **4. Hyperparameter Configuration**

In [9]:
HIDDEN_DIM  = 16
NUM_BLOCKS  = 1
HEAD_DIM    = 8
DROPOUT     = 0.7
BATCH_SIZE  = 128
LR          = 3e-4
EPOCHS      = 120
PATIENCE    = 15
LR_FACTOR   = 0.5
LR_PATIENCE = 5
LR_MIN      = 1e-5

## **5. Training**

In [10]:
def residual_block(x, units, dropout):
    h = Dense(units, activation='relu')(x)
    h = BatchNormalization()(h)
    h = Dropout(dropout)(h)
    h = Dense(units)(h)
    h = BatchNormalization()(h)
    return tf.keras.layers.Activation('relu')(Add()([x, h]))


inputs = Input(shape=(X_train.shape[1],))
x = Dense(HIDDEN_DIM, activation='relu')(inputs)
x = BatchNormalization()(x)
for _ in range(NUM_BLOCKS):
    x = residual_block(x, HIDDEN_DIM, DROPOUT)
x = Dense(HEAD_DIM, activation='relu')(x)
x = Dropout(DROPOUT)(x)
output = Dense(1, activation='sigmoid')(x)

model = Model(inputs=inputs, outputs=output)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=LR),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='val_auc', patience=PATIENCE, restore_best_weights=True, mode='max'),
    tf.keras.callbacks.ReduceLROnPlateau(monitor='val_auc', factor=LR_FACTOR, patience=LR_PATIENCE, min_lr=LR_MIN, mode='max'),
]

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=callbacks,
    verbose=1
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.6336 - auc: 0.4913 - loss: 1.1026 - val_accuracy: 0.7000 - val_auc: 0.4801 - val_loss: 0.6015 - learning_rate: 3.0000e-04
Epoch 2/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6748 - auc: 0.4989 - loss: 0.9484 - val_accuracy: 0.7406 - val_auc: 0.4931 - val_loss: 0.5669 - learning_rate: 3.0000e-04
Epoch 3/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6893 - auc: 0.5006 - loss: 0.8873 - val_accuracy: 0.7664 - val_auc: 0.5041 - val_loss: 0.5430 - learning_rate: 3.0000e-04
Epoch 4/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7184 - auc: 0.4978 - loss: 0.8191 - val_accuracy: 0.7906 - val_auc: 0.5182 - val_loss: 0.5249 - learning_rate: 3.0000e-04
Epoch 5/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7326 - auc: 0.5287 - loss: 0.7561 - val_accuracy: 0.8039 - val_auc: 0.5326 - val_loss: 0.5095 - learning_rate: 3.0000e-04
Epoch 6/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - auc: 0.5059 - loss: 0.7176 - val_accuracy: 0.8234 - val_auc: 0.5479 - val_loss: 0.4950 - learning_rate: 3.0000e-04
Epoch 7/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7561 - auc: 0.5160 - loss: 0.6841 - val_accuracy: 0.8398 - val_auc: 0.5629 - val_loss: 0.4819 - learning_rate: 3.0000e-04
Epoch 8/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7762 - auc: 0.5035 - loss: 0.6586 - val_accuracy: 0.8461 - val_auc: 0.5764 - val_loss: 0.4723 - learning_rate: 3.0000e-04
Epoch 9/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7773 - auc: 0.5214 - loss: 0.6338 - val_accuracy: 0.8523 - val_auc: 0.5889 - val_loss: 0.4622 - learning_rate: 3.0000e-04
Epoch 10/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7826 - auc: 0.5211 - loss: 0.6256 - val_accuracy: 0.8578 - val_auc: 0.6003 - val_loss: 0.4545 - learning_rate: 3.0000e-04
Epoch 11/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7998 - auc: 0.5322 - loss: 0.5906 - val_accuracy: 0.8625 - val_auc: 0.6086 - val_loss: 0.4483 - learning_rate: 3.0000e-04
Epoch 12/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8057 - auc: 0.5433 - loss: 0.5709 - val_accuracy: 0.8680 - val_auc: 0.6166 - val_loss: 0.4414 - learning_rate: 3.0000e-04
Epoch 13/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8184 - auc: 0.5214 - loss: 0.5819 - val_accuracy: 0.8711 - val_auc: 0.6232 - val_loss: 0.4370 - learning_rate: 3.0000e-04
Epoch 14/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8219 - auc: 0.5291 - loss: 0.5696 - val_accuracy: 0.8727 - val_auc: 0.6298 - val_loss: 0.4336 - learning_rate: 3.0000e-04
Epoch 15/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8299 - auc: 0.5416 - loss: 0.5513 - val_accuracy: 0.8750 - val_auc: 0.6340 - val_loss: 0.4291 - learning_rate: 3.0000e-04
Epoch 16/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8318 - auc: 0.5577 - loss: 0.5357 - val_accuracy: 0.8773 - val_auc: 0.6391 - val_loss: 0.4250 - learning_rate: 3.0000e-04
Epoch 17/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8367 - auc: 0.5595 - loss: 0.5315 - val_accuracy: 0.8773 - val_auc: 0.6436 - val_loss: 0.4197 - learning_rate: 3.0000e-04
Epoch 18/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8424 - auc: 0.5615 - loss: 0.5219 - val_accuracy: 0.8773 - val_auc: 0.6473 - val_loss: 0.4154 - learning_rate: 3.0000e-04
Epoch 19/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8449 - auc: 0.5532 - loss: 0.5209 - val_accuracy: 0.8781 - val_auc: 0.6525 - val_loss: 0.4118 - learning_rate: 3.0000e-04
Epoch 20/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8508 - auc: 0.5633 - loss: 0.5095 - val_accuracy: 0.8781 - val_auc: 0.6547 - val_loss: 0.4090 - learning_rate: 3.0000e-04
Epoch 21/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8492 - auc: 0.5444 - loss: 0.5165 - val_accuracy: 0.8781 - val_auc: 0.6584 - val_loss: 0.4074 - learning_rate: 3.0000e-04
Epoch 22/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8537 - auc: 0.5552 - loss: 0.5087 - val_accuracy: 0.8781 - val_auc: 0.6642 - val_loss: 0.4054 - learning_rate: 3.0000e-04
Epoch 23/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8564 - auc: 0.5637 - loss: 0.4977 - val_accuracy: 0.8781 - val_auc: 0.6682 - val_loss: 0.4022 - learning_rate: 3.0000e-04
Epoch 24/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8559 - auc: 0.5695 - loss: 0.4955 - val_accuracy: 0.8773 - val_auc: 0.6718 - val_loss: 0.3990 - learning_rate: 3.0000e-04
Epoch 25/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8580 - auc: 0.5720 - loss: 0.4849 - val_accuracy: 0.8758 - val_auc: 0.6742 - val_loss: 0.3964 - learning_rate: 3.0000e-04
Epoch 26/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8643 - auc: 0.5653 - loss: 0.4881 - val_accuracy: 0.8758 - val_auc: 0.6776 - val_loss: 0.3952 - learning_rate: 3.0000e-04
Epoch 27/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8584 - auc: 0.5726 - loss: 0.4842 - val_accuracy: 0.8758 - val_auc: 0.6809 - val_loss: 0.3920 - learning_rate: 3.0000e-04
Epoch 28/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8598 - auc: 0.5694 - loss: 0.4755 - val_accuracy: 0.8766 - val_auc: 0.6840 - val_loss: 0.3895 - learning_rate: 3.0000e-04
Epoch 29/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8613 - auc: 0.5697 - loss: 0.4782 - val_accuracy: 0.8766 - val_auc: 0.6880 - val_loss: 0.3878 - learning_rate: 3.0000e-04
Epoch 30/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8617 - auc: 0.5780 - loss: 0.4774 - val_accuracy: 0.8766 - val_auc: 0.6901 - val_loss: 0.3860 - learning_rate: 3.0000e-04
Epoch 31/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8674 - auc: 0.5981 - loss: 0.4589 - val_accuracy: 0.8766 - val_auc: 0.6922 - val_loss: 0.3839 - learning_rate: 3.0000e-04
Epoch 32/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8672 - auc: 0.5935 - loss: 0.4624 - val_accuracy: 0.8766 - val_auc: 0.6941 - val_loss: 0.3816 - learning_rate: 3.0000e-04
Epoch 33/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8674 - auc: 0.5913 - loss: 0.4586 - val_accuracy: 0.8766 - val_auc: 0.6972 - val_loss: 0.3807 - learning_rate: 3.0000e-04
Epoch 34/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8687 - auc: 0.5881 - loss: 0.4596 - val_accuracy: 0.8766 - val_auc: 0.6998 - val_loss: 0.3786 - learning_rate: 3.0000e-04
Epoch 35/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8693 - auc: 0.5659 - loss: 0.4721 - val_accuracy: 0.8766 - val_auc: 0.7024 - val_loss: 0.3777 - learning_rate: 3.0000e-04
Epoch 36/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - auc: 0.6015 - loss: 0.4469 - val_accuracy: 0.8766 - val_auc: 0.7057 - val_loss: 0.3752 - learning_rate: 3.0000e-04
Epoch 37/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8701 - auc: 0.5906 - loss: 0.4512 - val_accuracy: 0.8766 - val_auc: 0.7066 - val_loss: 0.3739 - learning_rate: 3.0000e-04
Epoch 38/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8684 - auc: 0.5828 - loss: 0.4603 - val_accuracy: 0.8766 - val_auc: 0.7094 - val_loss: 0.3733 - learning_rate: 3.0000e-04
Epoch 39/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8729 - auc: 0.5977 - loss: 0.4477 - val_accuracy: 0.8766 - val_auc: 0.7104 - val_loss: 0.3721 - learning_rate: 3.0000e-04
Epoch 40/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8709 - auc: 0.5823 - loss: 0.4550 - val_accuracy: 0.8766 - val_auc: 0.7135 - val_loss: 0.3714 - learning_rate: 3.0000e-04
Epoch 41/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8705 - auc: 0.5973 - loss: 0.4376 - val_accuracy: 0.8766 - val_auc: 0.7159 - val_loss: 0.3700 - learning_rate: 3.0000e-04
Epoch 42/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8717 - auc: 0.6109 - loss: 0.4384 - val_accuracy: 0.8766 - val_auc: 0.7184 - val_loss: 0.3683 - learning_rate: 3.0000e-04
Epoch 43/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8727 - auc: 0.5978 - loss: 0.4423 - val_accuracy: 0.8766 - val_auc: 0.7205 - val_loss: 0.3671 - learning_rate: 3.0000e-04
Epoch 44/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8744 - auc: 0.6047 - loss: 0.4411 - val_accuracy: 0.8766 - val_auc: 0.7226 - val_loss: 0.3665 - learning_rate: 3.0000e-04
Epoch 45/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8742 - auc: 0.6180 - loss: 0.4279 - val_accuracy: 0.8766 - val_auc: 0.7244 - val_loss: 0.3653 - learning_rate: 3.0000e-04
Epoch 46/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8725 - auc: 0.6189 - loss: 0.4293 - val_accuracy: 0.8766 - val_auc: 0.7258 - val_loss: 0.3634 - learning_rate: 3.0000e-04
Epoch 47/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8730 - auc: 0.6072 - loss: 0.4288 - val_accuracy: 0.8766 - val_auc: 0.7278 - val_loss: 0.3625 - learning_rate: 3.0000e-04
Epoch 48/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8729 - auc: 0.6085 - loss: 0.4288 - val_accuracy: 0.8766 - val_auc: 0.7294 - val_loss: 0.3607 - learning_rate: 3.0000e-04
Epoch 49/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8727 - auc: 0.6291 - loss: 0.4167 - val_accuracy: 0.8766 - val_auc: 0.7305 - val_loss: 0.3586 - learning_rate: 3.0000e-04
Epoch 50/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - auc: 0.6087 - loss: 0.4311 - val_accuracy: 0.8766 - val_auc: 0.7323 - val_loss: 0.3573 - learning_rate: 3.0000e-04
Epoch 51/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8744 - auc: 0.6243 - loss: 0.4167 - val_accuracy: 0.8766 - val_auc: 0.7340 - val_loss: 0.3564 - learning_rate: 3.0000e-04
Epoch 52/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8740 - auc: 0.5851 - loss: 0.4438 - val_accuracy: 0.8766 - val_auc: 0.7348 - val_loss: 0.3567 - learning_rate: 3.0000e-04
Epoch 53/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8740 - auc: 0.6173 - loss: 0.4197 - val_accuracy: 0.8766 - val_auc: 0.7369 - val_loss: 0.3557 - learning_rate: 3.0000e-04
Epoch 54/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - auc: 0.6128 - loss: 0.4265 - val_accuracy: 0.8766 - val_auc: 0.7377 - val_loss: 0.3547 - learning_rate: 3.0000e-04
Epoch 55/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8748 - auc: 0.6122 - loss: 0.4176 - val_accuracy: 0.8766 - val_auc: 0.7397 - val_loss: 0.3540 - learning_rate: 3.0000e-04
Epoch 56/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8744 - auc: 0.6135 - loss: 0.4208 - val_accuracy: 0.8766 - val_auc: 0.7404 - val_loss: 0.3530 - learning_rate: 3.0000e-04
Epoch 57/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8754 - auc: 0.5989 - loss: 0.4291 - val_accuracy: 0.8766 - val_auc: 0.7411 - val_loss: 0.3535 - learning_rate: 3.0000e-04
Epoch 58/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8748 - auc: 0.6332 - loss: 0.4099 - val_accuracy: 0.8766 - val_auc: 0.7426 - val_loss: 0.3520 - learning_rate: 3.0000e-04
Epoch 59/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8732 - auc: 0.6109 - loss: 0.4182 - val_accuracy: 0.8766 - val_auc: 0.7424 - val_loss: 0.3509 - learning_rate: 3.0000e-04
Epoch 60/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8758 - auc: 0.6095 - loss: 0.4110 - val_accuracy: 0.8766 - val_auc: 0.7429 - val_loss: 0.3505 - learning_rate: 3.0000e-04
Epoch 61/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8750 - auc: 0.6298 - loss: 0.4081 - val_accuracy: 0.8766 - val_auc: 0.7451 - val_loss: 0.3496 - learning_rate: 3.0000e-04
Epoch 62/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - auc: 0.6342 - loss: 0.4000 - val_accuracy: 0.8766 - val_auc: 0.7455 - val_loss: 0.3488 - learning_rate: 3.0000e-04
Epoch 63/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8750 - auc: 0.6177 - loss: 0.4205 - val_accuracy: 0.8766 - val_auc: 0.7465 - val_loss: 0.3484 - learning_rate: 3.0000e-04
Epoch 64/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - auc: 0.6152 - loss: 0.4120 - val_accuracy: 0.8766 - val_auc: 0.7484 - val_loss: 0.3483 - learning_rate: 3.0000e-04
Epoch 65/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8752 - auc: 0.6276 - loss: 0.4128 - val_accuracy: 0.8766 - val_auc: 0.7480 - val_loss: 0.3481 - learning_rate: 3.0000e-04
Epoch 66/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8754 - auc: 0.6273 - loss: 0.4043 - val_accuracy: 0.8766 - val_auc: 0.7491 - val_loss: 0.3476 - learning_rate: 3.0000e-04
Epoch 67/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8758 - auc: 0.6271 - loss: 0.4058 - val_accuracy: 0.8766 - val_auc: 0.7485 - val_loss: 0.3472 - learning_rate: 3.0000e-04
Epoch 68/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8754 - auc: 0.6259 - loss: 0.4038 - val_accuracy: 0.8766 - val_auc: 0.7495 - val_loss: 0.3472 - learning_rate: 3.0000e-04
Epoch 69/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8748 - auc: 0.6301 - loss: 0.3994 - val_accuracy: 0.8766 - val_auc: 0.7499 - val_loss: 0.3468 - learning_rate: 3.0000e-04
Epoch 70/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8764 - auc: 0.6526 - loss: 0.3900 - val_accuracy: 0.8766 - val_auc: 0.7502 - val_loss: 0.3458 - learning_rate: 3.0000e-04
Epoch 71/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8756 - auc: 0.6405 - loss: 0.3929 - val_accuracy: 0.8766 - val_auc: 0.7506 - val_loss: 0.3442 - learning_rate: 3.0000e-04
Epoch 72/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8768 - auc: 0.6474 - loss: 0.3924 - val_accuracy: 0.8766 - val_auc: 0.7527 - val_loss: 0.3434 - learning_rate: 3.0000e-04
Epoch 73/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8754 - auc: 0.6319 - loss: 0.4005 - val_accuracy: 0.8766 - val_auc: 0.7536 - val_loss: 0.3431 - learning_rate: 3.0000e-04
Epoch 74/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8768 - auc: 0.6384 - loss: 0.3891 - val_accuracy: 0.8766 - val_auc: 0.7529 - val_loss: 0.3422 - learning_rate: 3.0000e-04
Epoch 75/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8768 - auc: 0.6282 - loss: 0.3983 - val_accuracy: 0.8766 - val_auc: 0.7546 - val_loss: 0.3423 - learning_rate: 3.0000e-04
Epoch 76/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8764 - auc: 0.6505 - loss: 0.3901 - val_accuracy: 0.8766 - val_auc: 0.7548 - val_loss: 0.3417 - learning_rate: 3.0000e-04
Epoch 77/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8762 - auc: 0.6252 - loss: 0.3979 - val_accuracy: 0.8766 - val_auc: 0.7546 - val_loss: 0.3412 - learning_rate: 3.0000e-04
Epoch 78/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8764 - auc: 0.6491 - loss: 0.3878 - val_accuracy: 0.8766 - val_auc: 0.7562 - val_loss: 0.3409 - learning_rate: 3.0000e-04
Epoch 79/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - auc: 0.6484 - loss: 0.3866 - val_accuracy: 0.8766 - val_auc: 0.7568 - val_loss: 0.3404 - learning_rate: 3.0000e-04
Epoch 80/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8752 - auc: 0.6524 - loss: 0.3822 - val_accuracy: 0.8766 - val_auc: 0.7558 - val_loss: 0.3398 - learning_rate: 3.0000e-04
Epoch 81/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8756 - auc: 0.6340 - loss: 0.3937 - val_accuracy: 0.8766 - val_auc: 0.7558 - val_loss: 0.3393 - learning_rate: 3.0000e-04
Epoch 82/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8760 - auc: 0.6517 - loss: 0.3905 - val_accuracy: 0.8766 - val_auc: 0.7577 - val_loss: 0.3396 - learning_rate: 3.0000e-04
Epoch 83/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8760 - auc: 0.6597 - loss: 0.3850 - val_accuracy: 0.8766 - val_auc: 0.7579 - val_loss: 0.3391 - learning_rate: 3.0000e-04
Epoch 84/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8760 - auc: 0.6609 - loss: 0.3871 - val_accuracy: 0.8766 - val_auc: 0.7579 - val_loss: 0.3387 - learning_rate: 3.0000e-04
Epoch 85/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8766 - auc: 0.6508 - loss: 0.3887 - val_accuracy: 0.8766 - val_auc: 0.7587 - val_loss: 0.3386 - learning_rate: 3.0000e-04
Epoch 86/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - auc: 0.6667 - loss: 0.3756 - val_accuracy: 0.8766 - val_auc: 0.7590 - val_loss: 0.3384 - learning_rate: 3.0000e-04
Epoch 87/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8764 - auc: 0.6478 - loss: 0.3814 - val_accuracy: 0.8766 - val_auc: 0.7591 - val_loss: 0.3379 - learning_rate: 3.0000e-04
Epoch 88/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - auc: 0.6520 - loss: 0.3839 - val_accuracy: 0.8766 - val_auc: 0.7589 - val_loss: 0.3379 - learning_rate: 3.0000e-04
Epoch 89/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8764 - auc: 0.6568 - loss: 0.3827 - val_accuracy: 0.8766 - val_auc: 0.7607 - val_loss: 0.3376 - learning_rate: 3.0000e-04
Epoch 90/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - auc: 0.6711 - loss: 0.3734 - val_accuracy: 0.8766 - val_auc: 0.7615 - val_loss: 0.3371 - learning_rate: 3.0000e-04
Epoch 91/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8764 - auc: 0.6663 - loss: 0.3798 - val_accuracy: 0.8766 - val_auc: 0.7612 - val_loss: 0.3362 - learning_rate: 3.0000e-04
Epoch 92/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8758 - auc: 0.6595 - loss: 0.3779 - val_accuracy: 0.8766 - val_auc: 0.7628 - val_loss: 0.3356 - learning_rate: 3.0000e-04
Epoch 93/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - auc: 0.6484 - loss: 0.3810 - val_accuracy: 0.8766 - val_auc: 0.7628 - val_loss: 0.3358 - learning_rate: 3.0000e-04
Epoch 94/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - auc: 0.6615 - loss: 0.3774 - val_accuracy: 0.8766 - val_auc: 0.7635 - val_loss: 0.3356 - learning_rate: 3.0000e-04
Epoch 95/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8764 - auc: 0.6657 - loss: 0.3752 - val_accuracy: 0.8766 - val_auc: 0.7647 - val_loss: 0.3353 - learning_rate: 3.0000e-04
Epoch 96/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - auc: 0.6774 - loss: 0.3735 - val_accuracy: 0.8766 - val_auc: 0.7646 - val_loss: 0.3344 - learning_rate: 3.0000e-04
Epoch 97/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8766 - auc: 0.6737 - loss: 0.3706 - val_accuracy: 0.8766 - val_auc: 0.7657 - val_loss: 0.3341 - learning_rate: 3.0000e-04
Epoch 98/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8760 - auc: 0.6693 - loss: 0.3750 - val_accuracy: 0.8766 - val_auc: 0.7663 - val_loss: 0.3340 - learning_rate: 3.0000e-04
Epoch 99/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8760 - auc: 0.6682 - loss: 0.3735 - val_accuracy: 0.8766 - val_auc: 0.7657 - val_loss: 0.3340 - learning_rate: 3.0000e-04
Epoch 100/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8760 - auc: 0.6597 - loss: 0.3737 - val_accuracy: 0.8766 - val_auc: 0.7658 - val_loss: 0.3335 - learning_rate: 3.0000e-04
Epoch 101/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8764 - auc: 0.6783 - loss: 0.3703 - val_accuracy: 0.8766 - val_auc: 0.7676 - val_loss: 0.3333 - learning_rate: 3.0000e-04
Epoch 102/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8766 - auc: 0.6731 - loss: 0.3717 - val_accuracy: 0.8766 - val_auc: 0.7675 - val_loss: 0.3330 - learning_rate: 3.0000e-04
Epoch 103/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8766 - auc: 0.6538 - loss: 0.3804 - val_accuracy: 0.8766 - val_auc: 0.7671 - val_loss: 0.3328 - learning_rate: 3.0000e-04
Epoch 104/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8760 - auc: 0.6722 - loss: 0.3710 - val_accuracy: 0.8766 - val_auc: 0.7680 - val_loss: 0.3326 - learning_rate: 3.0000e-04
Epoch 105/120
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - auc: 0.6842 - loss: 0.3652 - val_accuracy: 0.8766 - val_auc: 0.7680 - val_loss: 0.3317 - learning_rate: 3.0000e-04
Epoch 106/120

## **6. Predict Testing Dataset**

In [11]:
y_train_prob = model.predict(X_train).flatten()
y_test_prob  = model.predict(X_test).flatten()

160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

## **7. Evaluation**

In [12]:
y_pred        = (y_test_prob >= 0.5).astype(int)
acc           = accuracy_score(y_test, y_pred)
roc_auc_train = roc_auc_score(y_train, y_train_prob)
roc_auc_test  = roc_auc_score(y_test,  y_test_prob)
auc_gap       = roc_auc_train - roc_auc_test

summary = pd.DataFrame({
    'Metric': ['Accuracy (Test)', 'ROC-AUC (Train)', 'ROC-AUC (Test)', 'AUC Gap (Train-Test)'],
    'Score':  [round(acc, 4), round(roc_auc_train, 4), round(roc_auc_test, 4), round(auc_gap, 4)],
})
summary

                 Metric   Score
0       Accuracy (Test)  0.8762
1       ROC-AUC (Train)  0.7817
2        ROC-AUC (Test)  0.7380
3  AUC Gap (Train-Test)  0.0437

In [13]:
report_df = pd.DataFrame(
    classification_report(y_test, y_pred, target_names=['Not Converted (0)', 'Converted (1)'], output_dict=True)
).T.round(4)
report_df

c:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

                   precision  recall  f1-score    support
Not Converted (0)     0.0000  0.0000    0.0000   198.0000
Converted (1)         0.8762  1.0000    0.9340  1402.0000
accuracy              0.8762  0.8762    0.8762     0.8762
macro avg             0.4381  0.5000    0.4670  1600.0000
weighted avg          0.7678  0.8762    0.8185  1600.0000